CREATE MATERIALIZED VIEW analitico.mv_coloader_per_ind AS SELECT produto, coloader_analitico AS coloader, ano_f, mes_f, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4;
CREATE INDEX mv_coloader_per_ind_idx ON analitico.mv_coloader_per_ind (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_ind_periodo_idx ON analitico.mv_coloader_per_ind (produto,ano_f,mes_f,coloader);
CREATE MATERIALIZED VIEW analitico.mv_coloader_per_oferta AS SELECT DISTINCT produto, coloader_analitico AS coloader, ano_f, mes_f, nullif(btrim(coalesce(oferta,'')),'') AS oferta FROM analitico.mv_ofertas_periodo WHERE nullif(btrim(coalesce(oferta,'')),'') IS NOT NULL;
CREATE INDEX mv_coloader_per_oferta_idx ON analitico.mv_coloader_per_oferta (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_oferta_periodo_idx ON analitico.mv_coloader_per_oferta (produto,ano_f,mes_f,coloader,oferta);
CREATE MATERIALIZED VIEW analitico.mv_coloader_per_cliente AS SELECT produto, coloader_analitico AS coloader, ano_f, mes_f, cliente_analitico AS item, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4,5;
CREATE INDEX mv_coloader_per_cliente_idx ON analitico.mv_coloader_per_cliente (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_cliente_periodo_idx ON analitico.mv_coloader_per_cliente (produto,ano_f,mes_f,coloader);
CREATE MATERIALIZED VIEW analitico.mv_coloader_per_rota AS SELECT produto, coloader_analitico AS coloader, ano_f, mes_f, rota_analitica AS item, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4,5;
CREATE INDEX mv_coloader_per_rota_idx ON analitico.mv_coloader_per_rota (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_rota_periodo_idx ON analitico.mv_coloader_per_rota (produto,ano_f,mes_f,coloader);
CREATE MATERIALIZED VIEW analitico.mv_coloader_per_agente AS SELECT produto, coloader_analitico AS coloader, ano_f, mes_f, agente_analitico AS item, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4,5;
CREATE INDEX mv_coloader_per_agente_idx ON analitico.mv_coloader_per_agente (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_agente_periodo_idx ON analitico.mv_coloader_per_agente (produto,ano_f,mes_f,coloader);
CREATE MATERIALIZED VIEW analitico.mv_coloader_per_motivo AS SELECT produto, coloader_analitico AS coloader, ano_f, mes_f, motivo_perda_analitico AS motivo, count(*)::bigint AS reprovadas FROM analitico.mv_ofertas_periodo WHERE flag_reprovada=1 GROUP BY 1,2,3,4,5;
CREATE INDEX mv_coloader_per_motivo_idx ON analitico.mv_coloader_per_motivo (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_motivo_periodo_idx ON analitico.mv_coloader_per_motivo (produto,ano_f,mes_f,coloader);
CREATE MATERIALIZED VIEW analitico.mv_coloader_per_rota_cliente AS SELECT produto, coloader_analitico AS coloader, ano_f, mes_f, rota_analitica AS rota, cliente_analitico AS cliente, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4,5,6;
CREATE INDEX mv_coloader_per_rota_cliente_idx ON analitico.mv_coloader_per_rota_cliente (produto,coloader,ano_f,mes_f); CREATE INDEX mv_coloader_per_rota_cliente_periodo_idx ON analitico.mv_coloader_per_rota_cliente (produto,ano_f,mes_f,coloader);
REVOKE ALL ON analitico.mv_coloader_per_ind,analitico.mv_coloader_per_oferta,analitico.mv_coloader_per_cliente,analitico.mv_coloader_per_rota,analitico.mv_coloader_per_agente,analitico.mv_coloader_per_motivo,analitico.mv_coloader_per_rota_cliente FROM public,anon,authenticated;
GRANT ALL ON analitico.mv_coloader_per_ind,analitico.mv_coloader_per_oferta,analitico.mv_coloader_per_cliente,analitico.mv_coloader_per_rota,analitico.mv_coloader_per_agente,analitico.mv_coloader_per_motivo,analitico.mv_coloader_per_rota_cliente TO service_role;
CREATE OR REPLACE FUNCTION public.coloaders_analise_periodo_calc(p_coloader text DEFAULT 'Todos',p_anos integer[] DEFAULT NULL,p_meses integer[] DEFAULT NULL) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,analitico SET work_mem='64MB' AS $$
WITH prods AS (SELECT public.produtos_do_usuario() AS p), alvo AS (SELECT coalesce(nullif(btrim(p_coloader),''),'(Não informado)') AS c),
ind AS (SELECT coalesce(sum(m.rotas),0)::bigint rotas,count(distinct m.coloader)::bigint coloaders,coalesce(sum(m.aprovadas),0)::bigint aprovadas,coalesce(sum(m.reprovadas),0)::bigint reprovadas,coalesce(sum(m.em_analise),0)::bigint em_analise FROM analitico.mv_coloader_per_ind m,prods,alvo WHERE m.produto=any(prods.p) AND (p_coloader='Todos' OR m.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses))),
ofs AS (SELECT count(distinct o.oferta)::bigint ofertas FROM analitico.mv_coloader_per_oferta o,prods,alvo WHERE o.produto=any(prods.p) AND (p_coloader='Todos' OR o.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR o.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR o.mes_f=any(p_meses))),
cli_all AS (SELECT c.item,sum(c.rotas)::bigint rotas,sum(c.aprovadas)::bigint aprovadas,sum(c.reprovadas)::bigint reprovadas,sum(c.em_analise)::bigint em_analise FROM analitico.mv_coloader_per_cliente c,prods,alvo WHERE c.produto=any(prods.p) AND (p_coloader='Todos' OR c.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR c.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR c.mes_f=any(p_meses)) GROUP BY c.item),
rot_all AS (SELECT r.item,sum(r.rotas)::bigint rotas,sum(r.aprovadas)::bigint aprovadas,sum(r.reprovadas)::bigint reprovadas,sum(r.em_analise)::bigint em_analise FROM analitico.mv_coloader_per_rota r,prods,alvo WHERE r.produto=any(prods.p) AND (p_coloader='Todos' OR r.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR r.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR r.mes_f=any(p_meses)) GROUP BY r.item),
age_all AS (SELECT a.item,sum(a.rotas)::bigint rotas,sum(a.aprovadas)::bigint aprovadas,sum(a.reprovadas)::bigint reprovadas,sum(a.em_analise)::bigint em_analise FROM analitico.mv_coloader_per_agente a,prods,alvo WHERE a.produto=any(prods.p) AND (p_coloader='Todos' OR a.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR a.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR a.mes_f=any(p_meses)) GROUP BY a.item),
mot_all AS (SELECT m.motivo,sum(m.reprovadas)::bigint reprovadas FROM analitico.mv_coloader_per_motivo m,prods,alvo WHERE m.produto=any(prods.p) AND (p_coloader='Todos' OR m.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY m.motivo),
rc_all AS (SELECT x.rota,x.cliente,sum(x.rotas)::bigint rotas,sum(x.aprovadas)::bigint aprovadas,sum(x.reprovadas)::bigint reprovadas,sum(x.em_analise)::bigint em_analise FROM analitico.mv_coloader_per_rota_cliente x,prods,alvo WHERE x.produto=any(prods.p) AND (p_coloader='Todos' OR x.coloader=alvo.c) AND (coalesce(cardinality(p_anos),0)=0 OR x.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR x.mes_f=any(p_meses)) GROUP BY x.rota,x.cliente),
indicadores AS (SELECT i.rotas,o.ofertas,(SELECT count(*) FROM cli_all)::bigint clientes,(SELECT count(*) FROM rot_all)::bigint rotas_distintas,i.coloaders,i.aprovadas,i.reprovadas,i.em_analise FROM ind i CROSS JOIN ofs o)
SELECT jsonb_build_object('indicadores',(SELECT to_jsonb(i) FROM indicadores i),'mediaAprovadas',coalesce((SELECT sum(m.aprovadas) FROM analitico.mv_cliente_media_geral m,prods WHERE m.produto=any(prods.p)),0),'mediaReprovadas',coalesce((SELECT sum(m.reprovadas) FROM analitico.mv_cliente_media_geral m,prods WHERE m.produto=any(prods.p)),0),'rotas',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.rotas DESC,x.item) FROM (SELECT * FROM rot_all ORDER BY rotas DESC,item LIMIT 10)x),'[]'::jsonb),'clientes',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.rotas DESC,x.item) FROM (SELECT * FROM cli_all ORDER BY rotas DESC,item LIMIT 10)x),'[]'::jsonb),'agentes',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.rotas DESC,x.item) FROM (SELECT * FROM age_all ORDER BY rotas DESC,item LIMIT 10)x),'[]'::jsonb),'motivosTotal',(SELECT reprovadas FROM indicadores),'motivos',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.reprovadas DESC,x.motivo) FROM (SELECT * FROM mot_all ORDER BY reprovadas DESC,motivo LIMIT 10)x),'[]'::jsonb),'rotaCliente',coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.reprovadas DESC,x.rotas DESC,x.rota,x.cliente) FROM (SELECT * FROM rc_all ORDER BY reprovadas DESC,rotas DESC,rota,cliente LIMIT 10)x),'[]'::jsonb)); $$;
REVOKE ALL ON FUNCTION public.coloaders_analise_periodo_calc(text,integer[],integer[]) FROM public,anon,authenticated;
CREATE OR REPLACE FUNCTION public.atualizar_analises_periodo() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,analitico AS $$ BEGIN
REFRESH MATERIALIZED VIEW analitico.mv_agente_dt; REFRESH MATERIALIZED VIEW analitico.mv_rota_dt; REFRESH MATERIALIZED VIEW analitico.mv_ofertas_periodo; REFRESH MATERIALIZED VIEW analitico.mv_analista_per; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_oferta; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_coloader; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_rota_agente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_coloader; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_rota_cliente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_mes; REFRESH MATERIALIZED VIEW analitico.mv_qualidade_resumo_per; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_oferta; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_coloader; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_rota_coloader; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_oferta; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_rota_cliente; END $$;
NOTIFY pgrst,'reload schema';