CREATE MATERIALIZED VIEW analitico.mv_rota_per_cc AS SELECT produto, ano_f, mes_f, pais_origem_f AS pais_origem, porto_origem, pais_destino_f AS pais_destino, porto_destino, rota_analitica AS rota, cliente_analitico AS cliente, coloader_analitico AS coloader, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4,5,6,7,8,9,10;
CREATE MATERIALIZED VIEW analitico.mv_rota_per_agente AS SELECT produto, ano_f, mes_f, pais_origem_f AS pais_origem, porto_origem, pais_destino_f AS pais_destino, porto_destino, rota_analitica AS rota, agente_analitico AS agente, count(*)::bigint AS rotas, coalesce(sum(flag_aprovada),0)::bigint AS aprovadas, coalesce(sum(flag_reprovada),0)::bigint AS reprovadas, coalesce(sum(flag_em_analise),0)::bigint AS em_analise FROM analitico.mv_ofertas_periodo GROUP BY 1,2,3,4,5,6,7,8,9;
CREATE MATERIALIZED VIEW analitico.mv_rota_per_motivo AS SELECT produto, ano_f, mes_f, pais_origem_f AS pais_origem, porto_origem, pais_destino_f AS pais_destino, porto_destino, rota_analitica AS rota, motivo_perda_analitico AS motivo, count(*)::bigint AS reprovadas FROM analitico.mv_ofertas_periodo WHERE flag_reprovada=1 GROUP BY 1,2,3,4,5,6,7,8,9;
CREATE MATERIALIZED VIEW analitico.mv_rota_per_oferta AS SELECT DISTINCT produto, ano_f, mes_f, pais_origem_f AS pais_origem, porto_origem, pais_destino_f AS pais_destino, porto_destino, rota_analitica AS rota, nullif(btrim(coalesce(oferta,'')),'') AS oferta FROM analitico.mv_ofertas_periodo WHERE nullif(btrim(coalesce(oferta,'')),'') IS NOT NULL;
CREATE INDEX mv_rota_per_cc_idx ON analitico.mv_rota_per_cc (produto, ano_f, mes_f, rota);
CREATE INDEX mv_rota_per_agente_idx ON analitico.mv_rota_per_agente (produto, ano_f, mes_f, rota);
CREATE INDEX mv_rota_per_motivo_idx ON analitico.mv_rota_per_motivo (produto, ano_f, mes_f, rota);
CREATE INDEX mv_rota_per_oferta_idx ON analitico.mv_rota_per_oferta (produto, ano_f, mes_f, rota);
REVOKE ALL ON analitico.mv_rota_per_cc, analitico.mv_rota_per_agente, analitico.mv_rota_per_motivo, analitico.mv_rota_per_oferta FROM public, anon, authenticated;
GRANT ALL ON analitico.mv_rota_per_cc, analitico.mv_rota_per_agente, analitico.mv_rota_per_motivo, analitico.mv_rota_per_oferta TO service_role;

CREATE OR REPLACE FUNCTION public.rotas_analise_periodo_calc(p_pais_origem text DEFAULT 'Todos', p_porto_origem text DEFAULT 'Todos', p_pais_destino text DEFAULT 'Todos', p_porto_destino text DEFAULT 'Todos', p_rota text DEFAULT 'Todos', p_anos integer[] DEFAULT NULL, p_meses integer[] DEFAULT NULL) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,analitico SET work_mem='64MB' AS $$
WITH pr AS (SELECT public.produtos_do_usuario() AS p),
cc AS MATERIALIZED (SELECT m.cliente, m.coloader, m.rota, sum(m.rotas)::bigint rotas, sum(m.aprovadas)::bigint aprovadas, sum(m.reprovadas)::bigint reprovadas, sum(m.em_analise)::bigint em_analise FROM analitico.mv_rota_per_cc m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY 1,2,3),
ind AS (SELECT coalesce(sum(rotas),0)::bigint rotas, (SELECT count(DISTINCT m.oferta) FROM analitico.mv_rota_per_oferta m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)))::bigint ofertas, count(DISTINCT cliente)::bigint clientes, count(DISTINCT rota)::bigint rotas_distintas, count(DISTINCT coloader)::bigint coloaders, coalesce(sum(aprovadas),0)::bigint aprovadas, coalesce(sum(reprovadas),0)::bigint reprovadas, coalesce(sum(em_analise),0)::bigint em_analise FROM cc),
col AS (SELECT coloader item, sum(rotas)::bigint rotas, sum(aprovadas)::bigint aprovadas, sum(reprovadas)::bigint reprovadas, sum(em_analise)::bigint em_analise FROM cc GROUP BY 1),
cli AS (SELECT cliente item, sum(rotas)::bigint rotas, sum(aprovadas)::bigint aprovadas, sum(reprovadas)::bigint reprovadas, sum(em_analise)::bigint em_analise FROM cc GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 10),
age AS (SELECT m.agente item, sum(m.rotas)::bigint rotas, sum(m.aprovadas)::bigint aprovadas, sum(m.reprovadas)::bigint reprovadas, sum(m.em_analise)::bigint em_analise FROM analitico.mv_rota_per_agente m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 10),
mot AS (SELECT m.motivo, sum(m.reprovadas)::bigint reprovadas FROM analitico.mv_rota_per_motivo m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 10),
cc2 AS (SELECT cliente, coloader, sum(rotas)::bigint rotas, sum(aprovadas)::bigint aprovadas, sum(reprovadas)::bigint reprovadas, sum(em_analise)::bigint em_analise FROM cc GROUP BY 1,2 ORDER BY 5 DESC, 3 DESC, 1, 2 LIMIT 10)
SELECT jsonb_build_object('indicadores',(SELECT to_jsonb(i) FROM ind i),
'mediaAprovadas', coalesce((SELECT sum(g.aprovadas) FROM analitico.mv_cliente_media_geral g, pr WHERE g.produto=any(pr.p)),0),
'mediaReprovadas', coalesce((SELECT sum(g.reprovadas) FROM analitico.mv_cliente_media_geral g, pr WHERE g.produto=any(pr.p)),0),
'coloaders', coalesce((SELECT jsonb_agg(to_jsonb(c) ORDER BY c.rotas DESC, c.item) FROM col c),'[]'::jsonb),
'clientes', coalesce((SELECT jsonb_agg(to_jsonb(c) ORDER BY c.rotas DESC, c.item) FROM cli c),'[]'::jsonb),
'agentes', coalesce((SELECT jsonb_agg(to_jsonb(a) ORDER BY a.rotas DESC, a.item) FROM age a),'[]'::jsonb),
'motivosTotal', (SELECT reprovadas FROM ind),
'motivos', coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.reprovadas DESC, x.motivo) FROM mot x),'[]'::jsonb),
'clienteColoader', coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.reprovadas DESC, x.rotas DESC, x.cliente, x.coloader) FROM cc2 x),'[]'::jsonb)); $$;
REVOKE ALL ON FUNCTION public.rotas_analise_periodo_calc(text,text,text,text,text,integer[],integer[]) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rotas_analise_periodo_calc(text,text,text,text,text,integer[],integer[]) TO service_role;
CREATE OR REPLACE FUNCTION public.atualizar_analises_periodo() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,analitico AS $fn$ BEGIN
REFRESH MATERIALIZED VIEW analitico.mv_agente_dt; REFRESH MATERIALIZED VIEW analitico.mv_rota_dt; REFRESH MATERIALIZED VIEW analitico.mv_ofertas_periodo; REFRESH MATERIALIZED VIEW analitico.mv_analista_per; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_oferta; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_coloader; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_analista_per_rota_agente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_coloader; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_rota_cliente; REFRESH MATERIALIZED VIEW analitico.mv_motivo_per_mes; REFRESH MATERIALIZED VIEW analitico.mv_qualidade_resumo_per; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_oferta; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_coloader; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_agente_per_rota_coloader; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_ind; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_oferta; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_cliente; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_rota; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_coloader_per_rota_cliente; REFRESH MATERIALIZED VIEW analitico.mv_rota_per_cc; REFRESH MATERIALIZED VIEW analitico.mv_rota_per_agente; REFRESH MATERIALIZED VIEW analitico.mv_rota_per_motivo; REFRESH MATERIALIZED VIEW analitico.mv_rota_per_oferta; END$fn$;
NOTIFY pgrst, 'reload schema';