CREATE INDEX IF NOT EXISTS mv_rota_per_cc_mes_idx ON analitico.mv_rota_per_cc (produto, mes_f, ano_f, rota);
CREATE INDEX IF NOT EXISTS mv_rota_per_agente_mes_idx ON analitico.mv_rota_per_agente (produto, mes_f, ano_f, rota);
CREATE INDEX IF NOT EXISTS mv_rota_per_motivo_mes_idx ON analitico.mv_rota_per_motivo (produto, mes_f, ano_f, rota);
CREATE INDEX IF NOT EXISTS mv_rota_per_oferta_mes_idx ON analitico.mv_rota_per_oferta (produto, mes_f, ano_f, rota);

CREATE OR REPLACE FUNCTION public.rotas_analise_periodo_calc(p_pais_origem text DEFAULT 'Todos', p_porto_origem text DEFAULT 'Todos', p_pais_destino text DEFAULT 'Todos', p_porto_destino text DEFAULT 'Todos', p_rota text DEFAULT 'Todos', p_anos integer[] DEFAULT NULL, p_meses integer[] DEFAULT NULL) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,analitico SET work_mem='64MB' AS $$
WITH pr AS MATERIALIZED (SELECT public.produtos_do_usuario() AS p),
cc AS MATERIALIZED (SELECT m.cliente, m.coloader, m.rota, sum(m.rotas)::bigint rotas, sum(m.aprovadas)::bigint aprovadas, sum(m.reprovadas)::bigint reprovadas, sum(m.em_analise)::bigint em_analise FROM analitico.mv_rota_per_cc m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY 1,2,3),
ind AS (SELECT coalesce(sum(rotas),0)::bigint rotas, (SELECT count(DISTINCT m.oferta) FROM analitico.mv_rota_per_oferta m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)))::bigint ofertas, count(DISTINCT cliente)::bigint clientes, count(DISTINCT rota)::bigint rotas_distintas, count(DISTINCT coloader)::bigint coloaders, coalesce(sum(aprovadas),0)::bigint aprovadas, coalesce(sum(reprovadas),0)::bigint reprovadas, coalesce(sum(em_analise),0)::bigint em_analise FROM cc),
col AS (SELECT coloader item, sum(rotas)::bigint rotas, sum(aprovadas)::bigint aprovadas, sum(reprovadas)::bigint reprovadas, sum(em_analise)::bigint em_analise FROM cc GROUP BY 1),
cli AS (SELECT cliente item, sum(rotas)::bigint rotas, sum(aprovadas)::bigint aprovadas, sum(reprovadas)::bigint reprovadas, sum(em_analise)::bigint em_analise FROM cc GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 10),
age AS (SELECT m.agente item, sum(m.rotas)::bigint rotas, sum(m.aprovadas)::bigint aprovadas, sum(m.reprovadas)::bigint reprovadas, sum(m.em_analise)::bigint em_analise FROM analitico.mv_rota_per_agente m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 10),
mot AS (SELECT m.motivo, sum(m.reprovadas)::bigint reprovadas FROM analitico.mv_rota_per_motivo m, pr WHERE m.produto = any(pr.p) AND (p_pais_origem='Todos' OR m.pais_origem=p_pais_origem) AND (p_porto_origem='Todos' OR m.porto_origem=p_porto_origem) AND (p_pais_destino='Todos' OR m.pais_destino=p_pais_destino) AND (p_porto_destino='Todos' OR m.porto_destino=p_porto_destino) AND (p_rota='Todos' OR m.rota=p_rota) AND (coalesce(cardinality(p_anos),0)=0 OR m.ano_f=any(p_anos)) AND (coalesce(cardinality(p_meses),0)=0 OR m.mes_f=any(p_meses)) GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 10),
cc2 AS (SELECT cliente, coloader, sum(rotas)::bigint rotas, sum(aprovadas)::bigint aprovadas, sum(reprovadas)::bigint reprovadas, sum(em_analise)::bigint em_analise FROM cc GROUP BY 1,2 ORDER BY 5 DESC, 3 DESC, 1, 2 LIMIT 10)
SELECT jsonb_build_object('indicadores',(SELECT to_jsonb(i) FROM ind i),
'mediaAprovadas', coalesce((SELECT sum(g.aprovadas) FROM analitico.mv_cliente_media_geral g, pr WHERE g.produto=any(pr.p)),0),
'mediaReprovadas', coalesce((SELECT sum(g.reprovadas) FROM analitico.mv_cliente_media_geral g, pr WHERE g.produto=any(pr.p)),0),
'coloaders', coalesce((SELECT jsonb_agg(to_jsonb(c) ORDER BY c.rotas DESC, c.item) FROM col c),'[]'::jsonb),
'clientes', coalesce((SELECT jsonb_agg(to_jsonb(c) ORDER BY c.rotas DESC, c.item) FROM cli c),'[]'::jsonb),
'agentes', coalesce((SELECT jsonb_agg(to_jsonb(a) ORDER BY a.rotas DESC, a.item) FROM age a),'[]'::jsonb),
'motivosTotal', (SELECT reprovadas FROM ind),
'motivos', coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.reprovadas DESC, x.motivo) FROM mot x),'[]'::jsonb),
'clienteColoader', coalesce((SELECT jsonb_agg(to_jsonb(x) ORDER BY x.reprovadas DESC, x.rotas DESC, x.cliente, x.coloader) FROM cc2 x),'[]'::jsonb)); $$;
REVOKE ALL ON FUNCTION public.rotas_analise_periodo_calc(text,text,text,text,text,integer[],integer[]) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rotas_analise_periodo_calc(text,text,text,text,text,integer[],integer[]) TO service_role;
NOTIFY pgrst, 'reload schema';