/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedAnalistasRouteImport } from './routes/_authenticated/analistas'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedClientes_por_clienteRouteImport } from './routes/_authenticated/clientes_por_cliente'
import { Route as AuthenticatedColoadersRouteImport } from './routes/_authenticated/coloaders'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCotacoesRouteImport } from './routes/_authenticated/cotacoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMotivosPerdaRouteImport } from './routes/_authenticated/motivos-perda'
import { Route as AuthenticatedQualidadeDadosRouteImport } from './routes/_authenticated/qualidade-dados'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalistasRoute = AuthenticatedAnalistasRouteImport.update({
  id: '/analistas',
  path: '/analistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientes_por_clienteRoute =
  AuthenticatedClientes_por_clienteRouteImport.update({
    id: '/clientes_por_cliente',
    path: '/clientes_por_cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColoadersRoute = AuthenticatedColoadersRouteImport.update({
  id: '/coloaders',
  path: '/coloaders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesRoute = AuthenticatedCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotivosPerdaRoute =
  AuthenticatedMotivosPerdaRouteImport.update({
    id: '/motivos-perda',
    path: '/motivos-perda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQualidadeDadosRoute =
  AuthenticatedQualidadeDadosRouteImport.update({
    id: '/qualidade-dados',
    path: '/qualidade-dados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/analistas': typeof AuthenticatedAnalistasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes_por_cliente': typeof AuthenticatedClientes_por_clienteRoute
  '/coloaders': typeof AuthenticatedColoadersRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/motivos-perda': typeof AuthenticatedMotivosPerdaRoute
  '/qualidade-dados': typeof AuthenticatedQualidadeDadosRoute
  '/rotas': typeof AuthenticatedRotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/analistas': typeof AuthenticatedAnalistasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes_por_cliente': typeof AuthenticatedClientes_por_clienteRoute
  '/coloaders': typeof AuthenticatedColoadersRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/motivos-perda': typeof AuthenticatedMotivosPerdaRoute
  '/qualidade-dados': typeof AuthenticatedQualidadeDadosRoute
  '/rotas': typeof AuthenticatedRotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/analistas': typeof AuthenticatedAnalistasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/clientes_por_cliente': typeof AuthenticatedClientes_por_clienteRoute
  '/_authenticated/coloaders': typeof AuthenticatedColoadersRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cotacoes': typeof AuthenticatedCotacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/motivos-perda': typeof AuthenticatedMotivosPerdaRoute
  '/_authenticated/qualidade-dados': typeof AuthenticatedQualidadeDadosRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agentes'
    | '/analistas'
    | '/clientes'
    | '/clientes_por_cliente'
    | '/coloaders'
    | '/configuracoes'
    | '/cotacoes'
    | '/dashboard'
    | '/motivos-perda'
    | '/qualidade-dados'
    | '/rotas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agentes'
    | '/analistas'
    | '/clientes'
    | '/clientes_por_cliente'
    | '/coloaders'
    | '/configuracoes'
    | '/cotacoes'
    | '/dashboard'
    | '/motivos-perda'
    | '/qualidade-dados'
    | '/rotas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agentes'
    | '/_authenticated/analistas'
    | '/_authenticated/clientes'
    | '/_authenticated/clientes_por_cliente'
    | '/_authenticated/coloaders'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cotacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/motivos-perda'
    | '/_authenticated/qualidade-dados'
    | '/_authenticated/rotas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analistas': {
      id: '/_authenticated/analistas'
      path: '/analistas'
      fullPath: '/analistas'
      preLoaderRoute: typeof AuthenticatedAnalistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes_por_cliente': {
      id: '/_authenticated/clientes_por_cliente'
      path: '/clientes_por_cliente'
      fullPath: '/clientes_por_cliente'
      preLoaderRoute: typeof AuthenticatedClientes_por_clienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coloaders': {
      id: '/_authenticated/coloaders'
      path: '/coloaders'
      fullPath: '/coloaders'
      preLoaderRoute: typeof AuthenticatedColoadersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes': {
      id: '/_authenticated/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof AuthenticatedCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivos-perda': {
      id: '/_authenticated/motivos-perda'
      path: '/motivos-perda'
      fullPath: '/motivos-perda'
      preLoaderRoute: typeof AuthenticatedMotivosPerdaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qualidade-dados': {
      id: '/_authenticated/qualidade-dados'
      path: '/qualidade-dados'
      fullPath: '/qualidade-dados'
      preLoaderRoute: typeof AuthenticatedQualidadeDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedAnalistasRoute: typeof AuthenticatedAnalistasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedClientes_por_clienteRoute: typeof AuthenticatedClientes_por_clienteRoute
  AuthenticatedColoadersRoute: typeof AuthenticatedColoadersRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCotacoesRoute: typeof AuthenticatedCotacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMotivosPerdaRoute: typeof AuthenticatedMotivosPerdaRoute
  AuthenticatedQualidadeDadosRoute: typeof AuthenticatedQualidadeDadosRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedAnalistasRoute: AuthenticatedAnalistasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedClientes_por_clienteRoute:
    AuthenticatedClientes_por_clienteRoute,
  AuthenticatedColoadersRoute: AuthenticatedColoadersRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCotacoesRoute: AuthenticatedCotacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMotivosPerdaRoute: AuthenticatedMotivosPerdaRoute,
  AuthenticatedQualidadeDadosRoute: AuthenticatedQualidadeDadosRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
